// Debug testbench for RV core + DebugModule
// Extends the standard CXXRTL testbench with DMI bus driving
// to exercise halt, register read/write, CSR access, and resume.

#include <iostream>
#include <fstream>
#include <cstdint>
#include <cstring>
#include <string>
#include <stdio.h>

#include "tb.h"
#include "tb_cli.h"
#include "tb_jtag.h"

// Device-under-test model generated by CXXRTL:
#include "dut.cpp"
#include <cxxrtl/cxxrtl_vcd.h>

#ifndef TB_DEBUG
#define TB_DEBUG 0
#endif

#ifndef TB_DEBUG_CYCLES
#define TB_DEBUG_CYCLES 80
#endif

#if TB_DEBUG
#define TB_DBG(cycle, ...) do { if ((cycle) < TB_DEBUG_CYCLES) fprintf(logfile, __VA_ARGS__); } while (0)
#else
#define TB_DBG(cycle, ...) do { (void)(cycle); } while (0)
#endif

static constexpr uint32_t TB_BOOT_PC = 0x80000040u;

// DMI operations
static constexpr uint32_t DMI_OP_NOP   = 0;
static constexpr uint32_t DMI_OP_READ  = 1;
static constexpr uint32_t DMI_OP_WRITE = 2;

// DMI addresses
static constexpr uint32_t DMI_DATA0      = 0x04;
static constexpr uint32_t DMI_DMCONTROL  = 0x10;
static constexpr uint32_t DMI_DMSTATUS   = 0x11;
static constexpr uint32_t DMI_ABSTRACTCS = 0x16;
static constexpr uint32_t DMI_COMMAND    = 0x17;

// Abstract command: Access Register (cmdtype=0, aarsize=2)
static constexpr uint32_t AC_ACCESS_REG = 0x00200000; // cmdtype=0, aarsize=2 (32-bit)
static constexpr uint32_t AC_TRANSFER   = (1u << 17);
static constexpr uint32_t AC_WRITE      = (1u << 16);

// Register numbers for abstract commands
static constexpr uint32_t REGNO_GPR_BASE = 0x1000;
static constexpr uint32_t REGNO_CSR_BASE = 0x0000;

class tb_debug_top;

// Forward declarations for DMI helpers
static uint32_t dmi_read(tb_debug_top &tb, mem_io_state &memio, uint32_t addr);
static void dmi_write(tb_debug_top &tb, mem_io_state &memio, uint32_t addr, uint32_t data);

class tb_debug_top: public tb_top {
	cxxrtl_design::p_tb top;
	cxxrtl::vcd_writer vcd;
	std::ofstream waves_fd;

public:
	int64_t cycle;

	tb_debug_top(const tb_cli_args &args);
	void step(const tb_cli_args &args, mem_io_state &memio) override;
	void finish(const tb_cli_args &args);

	void set_trst_n(bool trst_n)     override {top.p_trst__n.set<bool>(trst_n);}
	void set_tck(bool tck)           override {top.p_tck.set<bool>(tck);}
	void set_tdi(bool tdi)           override {top.p_tdi.set<bool>(tdi);}
	void set_tms(bool tms)           override {top.p_tms.set<bool>(tms);}
	bool get_tdo()                   override {return top.p_tdo.get<bool>();}

	void set_irq(uint32_t mask)      override {top.p_irq.set<bool>(mask != 0);}
	void set_soft_irq(uint8_t mask)  override {top.p_soft__irq.set<uint32_t>(mask & 0x3u);}
	void set_timer_irq(uint8_t mask) override {top.p_timer__irq.set<uint32_t>(mask & 0x3u);}

	// Debug diagnostics - read internal CXXRTL signals
	uint32_t diag_CsrRegs_dpc()   { return top.p_cpu_2e_CsrRegs__dpc.get<uint32_t>(); }
	uint32_t diag_nextTrapPc()     { return top.p_cpu_2e_nextTrapPc.get<uint32_t>(); }
	uint32_t diag_debugHalted()    { return top.p_cpu_2e_dbg__halted.get<uint32_t>(); }
	uint32_t diag_dm_data0()       { return top.p_dm_2e_data0.get<uint32_t>(); }
	uint32_t diag_Iptr()           { return top.p_cpu_2e_Iptr.get<uint32_t>(); }

	// DMI access
	void dmi_set_req(uint32_t addr, uint32_t data, uint32_t op) {
		top.p_dmi__req__valid.set<bool>(true);
		top.p_dmi__req__addr.set<uint32_t>(addr);
		top.p_dmi__req__data.set<uint32_t>(data);
		top.p_dmi__req__op.set<uint32_t>(op);
	}
	void dmi_clear_req() {
		top.p_dmi__req__valid.set<bool>(false);
		top.p_dmi__req__addr.set<uint32_t>(0);
		top.p_dmi__req__data.set<uint32_t>(0);
		top.p_dmi__req__op.set<uint32_t>(0);
	}
	bool dmi_resp_valid() {
		return top.p_dmi__resp__valid.get<bool>();
	}
	uint32_t dmi_resp_data() {
		return top.p_dmi__resp__data.get<uint32_t>();
	}
};

tb_debug_top::tb_debug_top(const tb_cli_args &args): tb_top {args} {
	cycle = 0;
	if (args.dump_waves) {
		waves_fd.open(args.waves_path);
		cxxrtl::debug_items all_debug_items;
		cxxrtl::debug_scopes all_debug_scopes;
		top.debug_info(&all_debug_items, &all_debug_scopes, "");
		vcd.timescale(1, "us");
		vcd.add(all_debug_items);
	}

	// Initialize AXI bus to idle
	top.p_i__axi__ar__ready.set<bool>(true);
	top.p_i__axi__r__valid.set<bool>(false);
	top.p_i__axi__r__data.set<uint32_t>(0);
	top.p_i__axi__r__resp.set<uint32_t>(0);
	
	top.p_d__axi__aw__ready.set<bool>(true);
	top.p_d__axi__w__ready.set<bool>(false);
	top.p_d__axi__b__valid.set<bool>(false);
	top.p_d__axi__b__resp.set<uint32_t>(0);
	top.p_d__axi__ar__ready.set<bool>(true);
	top.p_d__axi__r__valid.set<bool>(false);
	top.p_d__axi__r__data.set<uint32_t>(0);
	top.p_d__axi__r__resp.set<uint32_t>(0);

	top.p_irq.set<bool>(false);
	top.p_soft__irq.set<uint32_t>(0);
	top.p_timer__irq.set<uint32_t>(0);

	// DMI idle
	top.p_dmi__req__valid.set<bool>(false);
	top.p_dmi__req__addr.set<uint32_t>(0);
	top.p_dmi__req__data.set<uint32_t>(0);
	top.p_dmi__req__op.set<uint32_t>(0);

	// Reset + initial clock pulse
	top.p_rst__n.set<bool>(false);
	top.step();
	top.p_clk.set<bool>(true);
	top.p_tck.set<bool>(true);
	top.step();
	top.p_clk.set<bool>(false);
	top.p_tck.set<bool>(false);
	top.p_trst__n.set<bool>(true);
	top.p_rst__n.set<bool>(true);
	top.p_cpu_2e_Iptr.set<uint32_t>(TB_BOOT_PC);
	top.p_cpu_2e_instrMemory__PcReg.set<uint32_t>(TB_BOOT_PC);
	top.step();
	top.step(); // workaround for github.com/YosysHQ/yosys/issues/2780
}

void tb_debug_top::step(const tb_cli_args &args, mem_io_state &memio) {
	top.p_clk.set<bool>(false);
	top.step();
	if (args.dump_waves)
		vcd.sample(cycle * 2);
	
	// Handle instruction fetch AXI transactions
	if (top.p_i__axi__ar__valid.get<bool>() && top.p_i__axi__ar__ready.get<bool>()) {
		bus_request req;
		req.addr = top.p_i__axi__ar__addr.get<uint32_t>();
		req.size = SIZE_WORD;
		req.write = false;
		req.excl = false;
		bus_response resp = mem_callback_i(*this, memio, req);
		top.p_i__axi__r__valid.set<bool>(true);
		top.p_i__axi__r__data.set<uint32_t>(resp.rdata);
		top.p_i__axi__r__resp.set<uint32_t>(resp.err ? 2u : 0u);
	} else if (top.p_i__axi__r__valid.get<bool>() && top.p_i__axi__r__ready.get<bool>()) {
		top.p_i__axi__r__valid.set<bool>(false);
	}
	
	// Handle data read AXI transactions
	static bool d_r_pending_valid = false;
	static uint32_t d_r_pending_data = 0;
	static uint32_t d_r_pending_resp = 0;

	bool d_r_was_valid = top.p_d__axi__r__valid.get<bool>();
	bool d_r_was_ready = top.p_d__axi__r__ready.get<bool>();
	bool d_r_busy = d_r_pending_valid || d_r_was_valid;
	top.p_d__axi__ar__ready.set<bool>(!d_r_busy);

	if (d_r_was_valid && d_r_was_ready) {
		top.p_d__axi__r__valid.set<bool>(false);
	}

	if (!d_r_was_valid && d_r_pending_valid) {
		top.p_d__axi__r__valid.set<bool>(true);
		top.p_d__axi__r__data.set<uint32_t>(d_r_pending_data);
		top.p_d__axi__r__resp.set<uint32_t>(d_r_pending_resp);
		d_r_pending_valid = false;
	}

	if (top.p_d__axi__ar__valid.get<bool>() && top.p_d__axi__ar__ready.get<bool>()) {
		bus_request req;
		req.addr = top.p_d__axi__ar__addr.get<uint32_t>();
		req.size = SIZE_WORD;
		req.write = false;
		req.excl = false;
		bus_response resp = mem_callback_d(*this, memio, req);
		d_r_pending_valid = true;
		d_r_pending_data = resp.rdata;
		d_r_pending_resp = resp.err ? 2u : 0u;
	}

	// Handle data write AXI transactions
	static bool aw_pending = false;
	static uint32_t aw_addr = 0;
	static bool w_pending = false;
	static uint32_t w_data = 0;
	static uint32_t w_strb = 0;
	
	if (top.p_d__axi__aw__valid.get<bool>() && top.p_d__axi__aw__ready.get<bool>()) {
		aw_pending = true;
		aw_addr = top.p_d__axi__aw__addr.get<uint32_t>();
		top.p_d__axi__w__ready.set<bool>(true);
	}
	
	if (top.p_d__axi__w__valid.get<bool>() && top.p_d__axi__w__ready.get<bool>()) {
		w_pending = true;
		w_data = top.p_d__axi__w__data.get<uint32_t>();
		w_strb = top.p_d__axi__w__strb.get<uint32_t>();
	}
	
	if (aw_pending && w_pending) {
		bus_response merged_resp;
		if (w_strb == 0x1u || w_strb == 0x2u || w_strb == 0x4u || w_strb == 0x8u) {
			int byte = (w_strb == 0x1u) ? 0 : (w_strb == 0x2u) ? 1 : (w_strb == 0x4u) ? 2 : 3;
			bus_request req;
			req.addr = aw_addr + (uint32_t)byte;
			req.size = SIZE_BYTE;
			req.write = true;
			req.excl = false;
			req.wdata = (w_data >> (8 * byte)) & 0xffu;
			merged_resp = mem_callback_d(*this, memio, req);
		} else if (w_strb == 0x3u || w_strb == 0xCu) {
			int half = (w_strb == 0x3u) ? 0 : 2;
			bus_request req;
			req.addr = aw_addr + (uint32_t)half;
			req.size = SIZE_HWORD;
			req.write = true;
			req.excl = false;
			req.wdata = (w_data >> (8 * half)) & 0xffffu;
			merged_resp = mem_callback_d(*this, memio, req);
		} else if (w_strb == 0xFu) {
			bus_request req;
			req.addr = aw_addr;
			req.size = SIZE_WORD;
			req.write = true;
			req.excl = false;
			req.wdata = w_data;
			merged_resp = mem_callback_d(*this, memio, req);
		} else {
			merged_resp.err = true;
		}
		top.p_d__axi__b__valid.set<bool>(true);
		top.p_d__axi__b__resp.set<uint32_t>(merged_resp.err ? 2u : 0u);
		aw_pending = false;
		w_pending = false;
		top.p_d__axi__w__ready.set<bool>(false);
	} else if (top.p_d__axi__b__valid.get<bool>() && top.p_d__axi__b__ready.get<bool>()) {
		top.p_d__axi__b__valid.set<bool>(false);
	}
	
	top.p_clk.set<bool>(true);
	top.step();
	top.step(); // workaround for github.com/YosysHQ/yosys/issues/2780
	if (args.dump_waves)
		vcd.sample(cycle * 2 + 1);

	++cycle;
}

void tb_debug_top::finish(const tb_cli_args &args) {
	if (args.dump_waves) {
		waves_fd << vcd.buffer;
		vcd.buffer.clear();
		waves_fd.close();
	}
}

// ----- DMI helper functions -----

static void step_one(tb_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	memio.step(tb);
	tb.step(args, memio);
}

static uint32_t dmi_read(tb_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t addr) {
	// Assert DMI read request
	tb.dmi_set_req(addr, 0, DMI_OP_READ);
	step_one(tb, args, memio);  // rising edge: resp latched
	uint32_t result = tb.dmi_resp_data();  // capture before clearing req
	tb.dmi_clear_req();
	step_one(tb, args, memio);  // let clear propagate
	return result;
}

static void dmi_write(tb_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t addr, uint32_t data) {
	tb.dmi_set_req(addr, data, DMI_OP_WRITE);
	step_one(tb, args, memio);
	tb.dmi_clear_req();
	step_one(tb, args, memio); // let it settle
}

// Read GPR via abstract command
static uint32_t debug_read_gpr(tb_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t reg_num) {
	uint32_t cmd = AC_ACCESS_REG | AC_TRANSFER | (REGNO_GPR_BASE + reg_num);
	dmi_write(tb, args, memio, DMI_COMMAND, cmd);
	return dmi_read(tb, args, memio, DMI_DATA0);
}

// Write GPR via abstract command
static void debug_write_gpr(tb_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t reg_num, uint32_t value) {
	dmi_write(tb, args, memio, DMI_DATA0, value);
	uint32_t cmd = AC_ACCESS_REG | AC_TRANSFER | AC_WRITE | (REGNO_GPR_BASE + reg_num);
	dmi_write(tb, args, memio, DMI_COMMAND, cmd);
}

// Read CSR via abstract command
static uint32_t debug_read_csr(tb_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t csr_addr) {
	uint32_t cmd = AC_ACCESS_REG | AC_TRANSFER | (REGNO_CSR_BASE + csr_addr);
	dmi_write(tb, args, memio, DMI_COMMAND, cmd);
	step_one(tb, args, memio);
	return dmi_read(tb, args, memio, DMI_DATA0);
}

// ----- Main test -----

int main(int argc, char **argv) {
	tb_cli_args args;
	tb_parse_args(argc, argv, args);

	mem_io_state memio(args);
	if (args.load_bin && TB_BOOT_PC >= MEM_BASE && TB_BOOT_PC < MEM_BASE + MEM_SIZE) {
		uint32_t load_offset = TB_BOOT_PC - MEM_BASE;
		memmove(memio.mem + load_offset, memio.mem, MEM_SIZE - load_offset);
		memset(memio.mem, 0, load_offset);
	}
	tb_debug_top tb(args);

	int test_result = 0;
	int total_tests = 0;
	int passed_tests = 0;

#define CHECK(name, cond) do { \
	total_tests++; \
	if (cond) { \
		passed_tests++; \
		fprintf(tb.logfile, "  [PASS] %s\n", name); \
	} else { \
		test_result = 1; \
		fprintf(tb.logfile, "  [FAIL] %s\n", name); \
	} \
} while(0)

	fprintf(tb.logfile, "[debug_test] Starting debug test\n");

	// ---- Phase 1: Let the CPU run for some cycles to set up registers ----
	fprintf(tb.logfile, "[debug_test] Running CPU for 40 cycles...\n");
	for (int i = 0; i < 40; i++) {
		step_one(tb, args, memio);
	}

	// ---- Phase 2: Activate DM and halt the core ----
	fprintf(tb.logfile, "[debug_test] Activating DM and requesting halt...\n");
	// Write dmcontrol: dmactive=1, haltreq=1
	dmi_write(tb, args, memio, DMI_DMCONTROL, (1u << 31) | 1u);
	
	// Wait for core to halt (poll dmstatus)
	bool halted = false;
	for (int i = 0; i < 20; i++) {
		step_one(tb, args, memio);
		uint32_t status = dmi_read(tb, args, memio, DMI_DMSTATUS);
		if (status & (1u << 9)) { // allhalted
			halted = true;
			fprintf(tb.logfile, "[debug_test] Core halted after %d poll cycles\n", i + 1);
			break;
		}
	}
	CHECK("core halts on halt_req", halted);

	// ---- Phase 3: Read GPRs ----
	fprintf(tb.logfile, "[debug_test] Reading GPRs via abstract commands...\n");
	
	// Check abstractcs: no error
	uint32_t acs = dmi_read(tb, args, memio, DMI_ABSTRACTCS);
	uint32_t cmderr_val = (acs >> 8) & 0x7;
	CHECK("abstractcs clean before GPR read", cmderr_val == 0);

	// Read x10 (a0) - should be 0x12345678 (set by test program)
	uint32_t x10_val = debug_read_gpr(tb, args, memio, 10);
	fprintf(tb.logfile, "  x10 (a0) = 0x%08x (expected 0x12345678)\n", x10_val);
	CHECK("read GPR x10 (a0)", x10_val == 0x12345678u);

	// Read x11 (a1) - should be 0xDEADBEEF
	uint32_t x11_val = debug_read_gpr(tb, args, memio, 11);
	fprintf(tb.logfile, "  x11 (a1) = 0x%08x (expected 0xDEADBEEF)\n", x11_val);
	CHECK("read GPR x11 (a1)", x11_val == 0xDEADBEEFu);

	// Read x12 (a2) - should be 0xCAFEBABE
	uint32_t x12_val = debug_read_gpr(tb, args, memio, 12);
	fprintf(tb.logfile, "  x12 (a2) = 0x%08x (expected 0xCAFEBABE)\n", x12_val);
	CHECK("read GPR x12 (a2)", x12_val == 0xCAFEBABEu);

	// Read x0 - should always be 0
	uint32_t x0_val = debug_read_gpr(tb, args, memio, 0);
	fprintf(tb.logfile, "  x0       = 0x%08x (expected 0x00000000)\n", x0_val);
	CHECK("read GPR x0 (zero)", x0_val == 0x00000000u);

	// Check abstractcs: still no error
	acs = dmi_read(tb, args, memio, DMI_ABSTRACTCS);
	cmderr_val = (acs >> 8) & 0x7;
	CHECK("abstractcs clean after GPR reads", cmderr_val == 0);

	// ---- Phase 4: Write GPR via abstract command ----
	fprintf(tb.logfile, "[debug_test] Writing x13 (a3) = 0x42424242 via abstract command...\n");
	debug_write_gpr(tb, args, memio, 13, 0x42424242u);

	// Verify write by reading back
	uint32_t x13_readback = debug_read_gpr(tb, args, memio, 13);
	fprintf(tb.logfile, "  x13 (a3) readback = 0x%08x (expected 0x42424242)\n", x13_readback);
	CHECK("write+read GPR x13 (a3)", x13_readback == 0x42424242u);

	// ---- Phase 5: Read CSR (dpc) ----
	fprintf(tb.logfile, "[debug_test] Reading CSR dpc (0x7B1)...\n");
	uint32_t dpc_val = debug_read_csr(tb, args, memio, 0x7B1);
	fprintf(tb.logfile, "  dpc = 0x%08x (should be in .text section)\n", dpc_val);
	CHECK("dpc is in .text (>= 0x80000040)", dpc_val >= 0x80000040u);

	// ---- Phase 6: Resume the core ----
	fprintf(tb.logfile, "[debug_test] Resuming core...\n");
	// Clear haltreq, set resumereq
	dmi_write(tb, args, memio, DMI_DMCONTROL, (1u << 30) | 1u);
	
	// Wait for core to resume
	bool resumed = false;
	for (int i = 0; i < 10; i++) {
		step_one(tb, args, memio);
		uint32_t status = dmi_read(tb, args, memio, DMI_DMSTATUS);
		if (status & (1u << 4)) { // anyrunning
			resumed = true;
			fprintf(tb.logfile, "[debug_test] Core resumed after %d poll cycles\n", i + 1);
			break;
		}
	}
	CHECK("core resumes on resume_req", resumed);

	// ---- Phase 7: Let CPU run until it exits ----
	fprintf(tb.logfile, "[debug_test] Running CPU to completion...\n");
	bool cpu_exited = false;
	for (int64_t i = 0; i < 1000; i++) {
		step_one(tb, args, memio);
		if (memio.exit_req) {
			cpu_exited = true;
			fprintf(tb.logfile, "[debug_test] CPU exited with code %d after " I64_FMT " cycles from resume\n", 
				memio.exit_code, i + 1);
			break;
		}
	}
	CHECK("CPU exits after resume", cpu_exited);
	CHECK("CPU exit code is 0 (PASS)", cpu_exited && memio.exit_code == 0);

	// ---- Summary ----
	fprintf(tb.logfile, "\n========================================\n");
	fprintf(tb.logfile, " Debug test: %d/%d tests passed\n", passed_tests, total_tests);
	fprintf(tb.logfile, "========================================\n");
	
	if (test_result == 0) {
		fprintf(tb.logfile, "CPU requested halt. Exit code 0\n");
	} else {
		fprintf(tb.logfile, "CPU requested halt. Exit code 1\n");
	}
	fprintf(tb.logfile, "Ran for " I64_FMT " cycles\n", tb.cycle);

	tb.finish(args);
	return test_result;
}
