// JTAG debug testbench for RV core + DebugModule + JtagDTM
// Drives debug operations through JTAG TAP (bitbang) instead of direct DMI.
// Exercises: IDCODE read, DTMCS read, DMI read/write via JTAG,
// halt/resume, GPR/CSR access, and verifies end-to-end JTAG→DTM→DM→Core path.

#include <iostream>
#include <fstream>
#include <cstdint>
#include <cstring>
#include <string>
#include <stdio.h>

#include "tb.h"
#include "tb_cli.h"
#include "tb_jtag.h"

// Device-under-test model generated by CXXRTL:
#include "dut.cpp"
#include <cxxrtl/cxxrtl_vcd.h>

#ifndef TB_DEBUG
#define TB_DEBUG 0
#endif

#ifndef TB_DEBUG_CYCLES
#define TB_DEBUG_CYCLES 8000
#endif

#if TB_DEBUG
#define TB_DBG(cycle, ...) do { if ((cycle) < TB_DEBUG_CYCLES) fprintf(logfile, __VA_ARGS__); } while (0)
#else
#define TB_DBG(cycle, ...) do { (void)(cycle); } while (0)
#endif

static constexpr uint32_t TB_BOOT_PC = 0x80000040u;

// JTAG IR values (5-bit)
static constexpr uint32_t IR_IDCODE = 0x01;
static constexpr uint32_t IR_DTMCS  = 0x10;
static constexpr uint32_t IR_DMI    = 0x11;
static constexpr uint32_t IR_BYPASS = 0x1F;

// DMI operations
static constexpr uint32_t DMI_OP_NOP   = 0;
static constexpr uint32_t DMI_OP_READ  = 1;
static constexpr uint32_t DMI_OP_WRITE = 2;

// DMI addresses
static constexpr uint32_t DMI_DATA0      = 0x04;
static constexpr uint32_t DMI_DMCONTROL  = 0x10;
static constexpr uint32_t DMI_DMSTATUS   = 0x11;
static constexpr uint32_t DMI_ABSTRACTCS = 0x16;
static constexpr uint32_t DMI_COMMAND    = 0x17;

// Abstract command constants
static constexpr uint32_t AC_ACCESS_REG = 0x00200000; // cmdtype=0, aarsize=2
static constexpr uint32_t AC_TRANSFER   = (1u << 17);
static constexpr uint32_t AC_WRITE      = (1u << 16);
static constexpr uint32_t REGNO_GPR_BASE = 0x1000;
static constexpr uint32_t REGNO_CSR_BASE = 0x0000;

// Number of system clock cycles to run per JTAG half-period
// This ensures CDC synchronizers have time to propagate
static constexpr int SYS_CLKS_PER_JTAG_HALF = 4;

class tb_jtag_debug_top;

class tb_jtag_debug_top: public tb_top {
	cxxrtl_design::p_tb top;
	cxxrtl::vcd_writer vcd;
	std::ofstream waves_fd;

public:
	int64_t cycle;

	tb_jtag_debug_top(const tb_cli_args &args);
	void step(const tb_cli_args &args, mem_io_state &memio) override;
	void finish(const tb_cli_args &args);

	void set_trst_n(bool trst_n)     override { top.p_trst__n.set<bool>(trst_n); }
	void set_tck(bool tck)           override { top.p_tck.set<bool>(tck); }
	void set_tdi(bool tdi)           override { top.p_tdi.set<bool>(tdi); }
	void set_tms(bool tms)           override { top.p_tms.set<bool>(tms); }
	bool get_tdo()                   override { return top.p_tdo.get<bool>(); }

	void set_irq(uint32_t mask)      override { top.p_irq.set<bool>(mask != 0); }
	void set_soft_irq(uint8_t mask)  override { top.p_soft__irq.set<uint32_t>(mask & 0x3u); }
	void set_timer_irq(uint8_t mask) override { top.p_timer__irq.set<uint32_t>(mask & 0x3u); }

	// Debug diagnostics - read internal CXXRTL signals
	uint32_t diag_CsrRegs_dpc()   { return top.p_cpu_2e_CsrRegs__dpc.get<uint32_t>(); }
	uint32_t diag_debugHalted()    { return top.p_cpu_2e_debugHalted.get<uint32_t>(); }
	uint32_t diag_dm_data0()       { return top.p_dm_2e_data0.get<uint32_t>(); }
	uint32_t diag_Iptr()           { return top.p_cpu_2e_Iptr.get<uint32_t>(); }
};

tb_jtag_debug_top::tb_jtag_debug_top(const tb_cli_args &args): tb_top {args} {
	cycle = 0;
	if (args.dump_waves) {
		waves_fd.open(args.waves_path);
		cxxrtl::debug_items all_debug_items;
		cxxrtl::debug_scopes all_debug_scopes;
		top.debug_info(&all_debug_items, &all_debug_scopes, "");
		vcd.timescale(1, "us");
		vcd.add(all_debug_items);
	}

	// Initialize AXI bus to idle
	top.p_i__axi__ar__ready.set<bool>(true);
	top.p_i__axi__r__valid.set<bool>(false);
	top.p_i__axi__r__data.set<uint32_t>(0);
	top.p_i__axi__r__resp.set<uint32_t>(0);
	
	top.p_d__axi__aw__ready.set<bool>(true);
	top.p_d__axi__w__ready.set<bool>(false);
	top.p_d__axi__b__valid.set<bool>(false);
	top.p_d__axi__b__resp.set<uint32_t>(0);
	top.p_d__axi__ar__ready.set<bool>(true);
	top.p_d__axi__r__valid.set<bool>(false);
	top.p_d__axi__r__data.set<uint32_t>(0);
	top.p_d__axi__r__resp.set<uint32_t>(0);

	top.p_irq.set<bool>(false);
	top.p_soft__irq.set<uint32_t>(0);
	top.p_timer__irq.set<uint32_t>(0);

	// JTAG idle state
	top.p_tck.set<bool>(false);
	top.p_tms.set<bool>(true);
	top.p_tdi.set<bool>(false);
	top.p_trst__n.set<bool>(false);

	// Reset + initial clock pulse
	top.p_rst__n.set<bool>(false);
	top.step();
	top.p_clk.set<bool>(true);
	top.step();
	top.p_clk.set<bool>(false);
	top.step();

	// Release resets
	top.p_trst__n.set<bool>(true);
	top.p_rst__n.set<bool>(true);
	top.p_cpu_2e_Iptr.set<uint32_t>(TB_BOOT_PC);
	top.p_cpu_2e_instrMemory__PcReg.set<uint32_t>(TB_BOOT_PC);
	top.step();
	top.step(); // workaround for github.com/YosysHQ/yosys/issues/2780
}

void tb_jtag_debug_top::step(const tb_cli_args &args, mem_io_state &memio) {
	top.p_clk.set<bool>(false);
	top.step();
	if (args.dump_waves)
		vcd.sample(cycle * 2);
	
	// Handle instruction fetch AXI transactions
	if (top.p_i__axi__ar__valid.get<bool>() && top.p_i__axi__ar__ready.get<bool>()) {
		bus_request req;
		req.addr = top.p_i__axi__ar__addr.get<uint32_t>();
		req.size = SIZE_WORD;
		req.write = false;
		req.excl = false;
		bus_response resp = mem_callback_i(*this, memio, req);
		top.p_i__axi__r__valid.set<bool>(true);
		top.p_i__axi__r__data.set<uint32_t>(resp.rdata);
		top.p_i__axi__r__resp.set<uint32_t>(resp.err ? 2u : 0u);
	} else if (top.p_i__axi__r__valid.get<bool>() && top.p_i__axi__r__ready.get<bool>()) {
		top.p_i__axi__r__valid.set<bool>(false);
	}
	
	// Handle data read AXI transactions
	static bool d_r_pending_valid = false;
	static uint32_t d_r_pending_data = 0;
	static uint32_t d_r_pending_resp = 0;

	bool d_r_was_valid = top.p_d__axi__r__valid.get<bool>();
	bool d_r_was_ready = top.p_d__axi__r__ready.get<bool>();
	bool d_r_busy = d_r_pending_valid || d_r_was_valid;
	top.p_d__axi__ar__ready.set<bool>(!d_r_busy);

	if (d_r_was_valid && d_r_was_ready) {
		top.p_d__axi__r__valid.set<bool>(false);
	}

	if (!d_r_was_valid && d_r_pending_valid) {
		top.p_d__axi__r__valid.set<bool>(true);
		top.p_d__axi__r__data.set<uint32_t>(d_r_pending_data);
		top.p_d__axi__r__resp.set<uint32_t>(d_r_pending_resp);
		d_r_pending_valid = false;
	}

	if (top.p_d__axi__ar__valid.get<bool>() && top.p_d__axi__ar__ready.get<bool>()) {
		bus_request req;
		req.addr = top.p_d__axi__ar__addr.get<uint32_t>();
		req.size = SIZE_WORD;
		req.write = false;
		req.excl = false;
		bus_response resp = mem_callback_d(*this, memio, req);
		d_r_pending_valid = true;
		d_r_pending_data = resp.rdata;
		d_r_pending_resp = resp.err ? 2u : 0u;
	}

	// Handle data write AXI transactions
	static bool aw_pending = false;
	static uint32_t aw_addr = 0;
	static bool w_pending = false;
	static uint32_t w_data = 0;
	static uint32_t w_strb = 0;
	
	if (top.p_d__axi__aw__valid.get<bool>() && top.p_d__axi__aw__ready.get<bool>()) {
		aw_pending = true;
		aw_addr = top.p_d__axi__aw__addr.get<uint32_t>();
		top.p_d__axi__w__ready.set<bool>(true);
	}
	
	if (top.p_d__axi__w__valid.get<bool>() && top.p_d__axi__w__ready.get<bool>()) {
		w_pending = true;
		w_data = top.p_d__axi__w__data.get<uint32_t>();
		w_strb = top.p_d__axi__w__strb.get<uint32_t>();
	}
	
	if (aw_pending && w_pending) {
		bus_response merged_resp;
		if (w_strb == 0x1u || w_strb == 0x2u || w_strb == 0x4u || w_strb == 0x8u) {
			int byte = (w_strb == 0x1u) ? 0 : (w_strb == 0x2u) ? 1 : (w_strb == 0x4u) ? 2 : 3;
			bus_request req;
			req.addr = aw_addr + (uint32_t)byte;
			req.size = SIZE_BYTE;
			req.write = true;
			req.excl = false;
			req.wdata = (w_data >> (8 * byte)) & 0xffu;
			merged_resp = mem_callback_d(*this, memio, req);
		} else if (w_strb == 0x3u || w_strb == 0xCu) {
			int half = (w_strb == 0x3u) ? 0 : 2;
			bus_request req;
			req.addr = aw_addr + (uint32_t)half;
			req.size = SIZE_HWORD;
			req.write = true;
			req.excl = false;
			req.wdata = (w_data >> (8 * half)) & 0xffffu;
			merged_resp = mem_callback_d(*this, memio, req);
		} else if (w_strb == 0xFu) {
			bus_request req;
			req.addr = aw_addr;
			req.size = SIZE_WORD;
			req.write = true;
			req.excl = false;
			req.wdata = w_data;
			merged_resp = mem_callback_d(*this, memio, req);
		} else {
			merged_resp.err = true;
		}
		top.p_d__axi__b__valid.set<bool>(true);
		top.p_d__axi__b__resp.set<uint32_t>(merged_resp.err ? 2u : 0u);
		aw_pending = false;
		w_pending = false;
		top.p_d__axi__w__ready.set<bool>(false);
	} else if (top.p_d__axi__b__valid.get<bool>() && top.p_d__axi__b__ready.get<bool>()) {
		top.p_d__axi__b__valid.set<bool>(false);
	}
	
	top.p_clk.set<bool>(true);
	top.step();
	top.step(); // workaround for github.com/YosysHQ/yosys/issues/2780
	if (args.dump_waves)
		vcd.sample(cycle * 2 + 1);

	++cycle;
}

void tb_jtag_debug_top::finish(const tb_cli_args &args) {
	if (args.dump_waves) {
		waves_fd << vcd.buffer;
		vcd.buffer.clear();
		waves_fd.close();
	}
}

// ========================================================================
// JTAG bitbang helpers
// ========================================================================

static FILE *logfile_g = nullptr;

// Forward declaration
static bool jtag_tick(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio,
                      bool tms, bool tdi);

// Wait in Run-Test-Idle with TCK toggling to let CDC handshake complete.
// Both CLK and TCK edges are needed: CLK for system-side synchronizers,
// TCK for JTAG-side synchronizers.
static void jtag_idle(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, int n_tck) {
	for (int i = 0; i < n_tck; i++)
		jtag_tick(tb, args, memio, false, false);  // TMS=0 stays in RTI
}

// Advance system clock N cycles (CPU + AXI + DM run, no JTAG activity)
static void sys_clk_cycles(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, int n) {
	for (int i = 0; i < n; i++) {
		memio.step(tb);
		tb.step(args, memio);
	}
}

// One JTAG TCK pulse: read TDO (from previous falling edge), then set
// TMS/TDI and pulse TCK. Per JTAG spec, TDO is valid from the previous
// falling edge and must be sampled BEFORE the next rising edge.
static bool jtag_tick(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio,
                      bool tms, bool tdi) {
	// Read TDO from PREVIOUS falling edge (valid now, before rising edge)
	bool tdo = tb.get_tdo();

	// Set inputs before rising edge
	tb.set_tms(tms);
	tb.set_tdi(tdi);

	// Run a few system clocks with TCK=0 to let CDC settle
	sys_clk_cycles(tb, args, memio, SYS_CLKS_PER_JTAG_HALF);

	// Rising edge of TCK (TAP state machine advances, shift registers shift)
	tb.set_tck(true);
	sys_clk_cycles(tb, args, memio, SYS_CLKS_PER_JTAG_HALF);

	// Falling edge of TCK (TDO register updates for NEXT read)
	tb.set_tck(false);
	sys_clk_cycles(tb, args, memio, 1);

	return tdo;
}

// Navigate to Test-Logic-Reset by holding TMS=1 for 5 clocks
static void jtag_reset(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	for (int i = 0; i < 5; i++)
		jtag_tick(tb, args, memio, true, false);
}

// Go from Test-Logic-Reset or Run-Test-Idle to Run-Test-Idle
static void jtag_goto_rti(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	jtag_tick(tb, args, memio, false, false);  // TMS=0 → RTI
}

// Navigate: RTI → Select-DR → Select-IR → Capture-IR → Shift-IR
static void jtag_goto_shift_ir(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	jtag_tick(tb, args, memio, true, false);   // RTI → Select-DR
	jtag_tick(tb, args, memio, true, false);   // Select-DR → Select-IR
	jtag_tick(tb, args, memio, false, false);  // Select-IR → Capture-IR
	jtag_tick(tb, args, memio, false, false);  // Capture-IR → Shift-IR
}

// Navigate: RTI → Select-DR → Capture-DR → Shift-DR
static void jtag_goto_shift_dr(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	jtag_tick(tb, args, memio, true, false);   // RTI → Select-DR
	jtag_tick(tb, args, memio, false, false);  // Select-DR → Capture-DR
	jtag_tick(tb, args, memio, false, false);  // Capture-DR → Shift-DR
}

// Shift 'nbits' bits (LSB first) and capture TDO output.
// On the last bit, TMS=1 to exit to Exit1-xR.
// Returns the captured shift-out data.
static uint64_t jtag_shift(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio,
                            uint64_t tdi_data, int nbits) {
	uint64_t tdo_data = 0;
	for (int i = 0; i < nbits; i++) {
		bool is_last = (i == nbits - 1);
		bool tdi_bit = (tdi_data >> i) & 1;
		bool tdo_bit = jtag_tick(tb, args, memio, is_last, tdi_bit);
		if (tdo_bit)
			tdo_data |= (1ULL << i);
	}
	return tdo_data;
}

// After shift (now in Exit1-xR), go through Update-xR → RTI
static void jtag_update_to_rti(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	jtag_tick(tb, args, memio, true, false);   // Exit1 → Update
	jtag_tick(tb, args, memio, false, false);  // Update → RTI
}

// Write JTAG IR register (5-bit)
static void jtag_write_ir(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio,
                           uint32_t ir_value) {
	jtag_goto_shift_ir(tb, args, memio);
	jtag_shift(tb, args, memio, ir_value & 0x1F, 5);
	jtag_update_to_rti(tb, args, memio);
}

// Read IDCODE (32-bit DR)
static uint32_t jtag_read_idcode(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	jtag_write_ir(tb, args, memio, IR_IDCODE);
	jtag_goto_shift_dr(tb, args, memio);
	uint64_t idcode = jtag_shift(tb, args, memio, 0, 32);
	jtag_update_to_rti(tb, args, memio);
	return (uint32_t)idcode;
}

// Read DTMCS (32-bit DR)
static uint32_t jtag_read_dtmcs(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio) {
	jtag_write_ir(tb, args, memio, IR_DTMCS);
	jtag_goto_shift_dr(tb, args, memio);
	uint64_t dtmcs = jtag_shift(tb, args, memio, 0, 32);
	jtag_update_to_rti(tb, args, memio);
	return (uint32_t)dtmcs;
}

// ========================================================================
// DMI access via JTAG
// ========================================================================
// DMI register format (41 bits, LSB first):
//   [1:0]  = op   (0=nop, 1=read, 2=write)
//   [33:2] = data (32 bits)
//   [40:34]= addr (7 bits)

// Perform a DMI transaction:
// 1. Select DMI IR
// 2. Shift in: addr | data | op
// 3. Update (triggers the DMI request in DTM)
// 4. Wait for CDC to propagate (run system clocks in RTI)
// 5. Capture-DR to read response: addr | resp_data | status

static uint32_t jtag_dmi_read(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio,
                               uint32_t addr) {
	// Select DMI register
	jtag_write_ir(tb, args, memio, IR_DMI);

	// Shift in DMI read request: op=1 (read), data=0, addr
	uint64_t dmi_in = ((uint64_t)(addr & 0x7F) << 34) | ((uint64_t)0 << 2) | DMI_OP_READ;
	jtag_goto_shift_dr(tb, args, memio);
	jtag_shift(tb, args, memio, dmi_in, 41);
	jtag_update_to_rti(tb, args, memio);

	// Wait for DMI transaction to complete through CDC
	// Need TCK edges for JTAG-domain synchronizers + CLK edges for system-domain
	jtag_idle(tb, args, memio, 8);

	// Read response: Capture-DR → Shift-DR (captures response into shift reg)
	jtag_goto_shift_dr(tb, args, memio);
	uint64_t dmi_out = jtag_shift(tb, args, memio, 0, 41);
	jtag_update_to_rti(tb, args, memio);

	uint32_t status = dmi_out & 0x3;
	uint32_t resp_data = (dmi_out >> 2) & 0xFFFFFFFF;

	if (status == 3) {
		fprintf(logfile_g, "  [WARN] DMI read addr=0x%02x: busy (status=3)\n", addr);
	} else if (status != 0) {
		fprintf(logfile_g, "  [WARN] DMI read addr=0x%02x: error (status=%u)\n", addr, status);
	}

	return resp_data;
}

static void jtag_dmi_write(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio,
                            uint32_t addr, uint32_t data) {
	// Select DMI register
	jtag_write_ir(tb, args, memio, IR_DMI);

	// Shift in DMI write request
	uint64_t dmi_in = ((uint64_t)(addr & 0x7F) << 34) | ((uint64_t)data << 2) | DMI_OP_WRITE;
	jtag_goto_shift_dr(tb, args, memio);
	jtag_shift(tb, args, memio, dmi_in, 41);
	jtag_update_to_rti(tb, args, memio);

	// Wait for CDC propagation (need TCK + CLK edges)
	jtag_idle(tb, args, memio, 8);
}

// Read GPR via abstract command through JTAG
static uint32_t jtag_debug_read_gpr(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t reg_num) {
	uint32_t cmd = AC_ACCESS_REG | AC_TRANSFER | (REGNO_GPR_BASE + reg_num);
	jtag_dmi_write(tb, args, memio, DMI_COMMAND, cmd);
	return jtag_dmi_read(tb, args, memio, DMI_DATA0);
}

// Write GPR via abstract command through JTAG
static void jtag_debug_write_gpr(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t reg_num, uint32_t value) {
	jtag_dmi_write(tb, args, memio, DMI_DATA0, value);
	uint32_t cmd = AC_ACCESS_REG | AC_TRANSFER | AC_WRITE | (REGNO_GPR_BASE + reg_num);
	jtag_dmi_write(tb, args, memio, DMI_COMMAND, cmd);
}

// Read CSR via abstract command through JTAG
static uint32_t jtag_debug_read_csr(tb_jtag_debug_top &tb, const tb_cli_args &args, mem_io_state &memio, uint32_t csr_addr) {
	uint32_t cmd = AC_ACCESS_REG | AC_TRANSFER | (REGNO_CSR_BASE + csr_addr);
	jtag_dmi_write(tb, args, memio, DMI_COMMAND, cmd);
	return jtag_dmi_read(tb, args, memio, DMI_DATA0);
}

// ----- Main test -----

int main(int argc, char **argv) {
	tb_cli_args args;
	tb_parse_args(argc, argv, args);

	mem_io_state memio(args);
	if (args.load_bin && TB_BOOT_PC >= MEM_BASE && TB_BOOT_PC < MEM_BASE + MEM_SIZE) {
		uint32_t load_offset = TB_BOOT_PC - MEM_BASE;
		memmove(memio.mem + load_offset, memio.mem, MEM_SIZE - load_offset);
		memset(memio.mem, 0, load_offset);
	}
	tb_jtag_debug_top tb(args);
	logfile_g = tb.logfile;

	int test_result = 0;
	int total_tests = 0;
	int passed_tests = 0;

#define CHECK(name, cond) do { \
	total_tests++; \
	if (cond) { \
		passed_tests++; \
		fprintf(tb.logfile, "  [PASS] %s\n", name); \
	} else { \
		test_result = 1; \
		fprintf(tb.logfile, "  [FAIL] %s\n", name); \
	} \
} while(0)

	fprintf(tb.logfile, "[jtag_test] Starting JTAG debug test\n");

	// ---- Phase 0: Reset JTAG TAP ----
	fprintf(tb.logfile, "[jtag_test] Resetting JTAG TAP...\n");
	jtag_reset(tb, args, memio);
	jtag_goto_rti(tb, args, memio);

	// ---- Phase 1: Read IDCODE ----
	fprintf(tb.logfile, "[jtag_test] Reading IDCODE via JTAG...\n");
	uint32_t idcode = jtag_read_idcode(tb, args, memio);
	fprintf(tb.logfile, "  IDCODE = 0x%08x (expected 0xDEADBEEF)\n", idcode);
	CHECK("IDCODE read", idcode == 0xDEADBEEFu);

	// ---- Phase 2: Read DTMCS ----
	fprintf(tb.logfile, "[jtag_test] Reading DTMCS via JTAG...\n");
	uint32_t dtmcs = jtag_read_dtmcs(tb, args, memio);
	uint32_t dtm_version = dtmcs & 0xF;
	uint32_t dtm_abits   = (dtmcs >> 4) & 0x3F;
	uint32_t dtm_idle    = (dtmcs >> 12) & 0x7;
	fprintf(tb.logfile, "  DTMCS = 0x%08x (version=%u, abits=%u, idle=%u)\n",
		dtmcs, dtm_version, dtm_abits, dtm_idle);
	CHECK("DTMCS version=1", dtm_version == 1);
	CHECK("DTMCS abits=7",   dtm_abits == 7);

	// ---- Phase 3: Let CPU run to set up test registers ----
	fprintf(tb.logfile, "[jtag_test] Running CPU for 40 cycles...\n");
	sys_clk_cycles(tb, args, memio, 40);

	// ---- Phase 4: Activate DM and halt via JTAG DMI ----
	fprintf(tb.logfile, "[jtag_test] Activating DM + halt via JTAG DMI...\n");
	jtag_dmi_write(tb, args, memio, DMI_DMCONTROL, (1u << 31) | 1u);

	// Poll dmstatus for halt
	bool halted = false;
	for (int i = 0; i < 20; i++) {
		sys_clk_cycles(tb, args, memio, 4);
		uint32_t status = jtag_dmi_read(tb, args, memio, DMI_DMSTATUS);
		if (status & (1u << 9)) { // allhalted
			halted = true;
			fprintf(tb.logfile, "[jtag_test] Core halted after %d JTAG polls\n", i + 1);
			break;
		}
	}
	CHECK("core halts via JTAG DMI", halted);

	// ---- Phase 5: Read GPRs via JTAG ----
	fprintf(tb.logfile, "[jtag_test] Reading GPRs via JTAG abstract commands...\n");

	uint32_t acs = jtag_dmi_read(tb, args, memio, DMI_ABSTRACTCS);
	uint32_t cmderr_val = (acs >> 8) & 0x7;
	CHECK("abstractcs clean before GPR read", cmderr_val == 0);

	uint32_t x10_val = jtag_debug_read_gpr(tb, args, memio, 10);
	fprintf(tb.logfile, "  x10 (a0) = 0x%08x (expected 0x12345678)\n", x10_val);
	CHECK("JTAG read GPR x10 (a0)", x10_val == 0x12345678u);

	uint32_t x11_val = jtag_debug_read_gpr(tb, args, memio, 11);
	fprintf(tb.logfile, "  x11 (a1) = 0x%08x (expected 0xDEADBEEF)\n", x11_val);
	CHECK("JTAG read GPR x11 (a1)", x11_val == 0xDEADBEEFu);

	uint32_t x12_val = jtag_debug_read_gpr(tb, args, memio, 12);
	fprintf(tb.logfile, "  x12 (a2) = 0x%08x (expected 0xCAFEBABE)\n", x12_val);
	CHECK("JTAG read GPR x12 (a2)", x12_val == 0xCAFEBABEu);

	uint32_t x0_val = jtag_debug_read_gpr(tb, args, memio, 0);
	fprintf(tb.logfile, "  x0       = 0x%08x (expected 0x00000000)\n", x0_val);
	CHECK("JTAG read GPR x0 (zero)", x0_val == 0x00000000u);

	acs = jtag_dmi_read(tb, args, memio, DMI_ABSTRACTCS);
	cmderr_val = (acs >> 8) & 0x7;
	CHECK("abstractcs clean after GPR reads", cmderr_val == 0);

	// ---- Phase 6: Write GPR via JTAG ----
	fprintf(tb.logfile, "[jtag_test] Writing x13 = 0x42424242 via JTAG...\n");
	jtag_debug_write_gpr(tb, args, memio, 13, 0x42424242u);

	uint32_t x13_readback = jtag_debug_read_gpr(tb, args, memio, 13);
	fprintf(tb.logfile, "  x13 readback = 0x%08x (expected 0x42424242)\n", x13_readback);
	CHECK("JTAG write+read GPR x13", x13_readback == 0x42424242u);

	// ---- Phase 7: Read CSR (dpc) via JTAG ----
	fprintf(tb.logfile, "[jtag_test] Reading CSR dpc (0x7B1) via JTAG...\n");
	uint32_t dpc_val = jtag_debug_read_csr(tb, args, memio, 0x7B1);
	fprintf(tb.logfile, "  dpc = 0x%08x (should be >= 0x80000040)\n", dpc_val);
	CHECK("JTAG dpc in .text", dpc_val >= 0x80000040u);

	// ---- Phase 8: Resume via JTAG ----
	fprintf(tb.logfile, "[jtag_test] Resuming core via JTAG...\n");
	jtag_dmi_write(tb, args, memio, DMI_DMCONTROL, (1u << 30) | 1u);

	bool resumed = false;
	for (int i = 0; i < 20; i++) {
		sys_clk_cycles(tb, args, memio, 4);
		uint32_t status = jtag_dmi_read(tb, args, memio, DMI_DMSTATUS);
		if (status & (1u << 4)) { // anyrunning
			resumed = true;
			fprintf(tb.logfile, "[jtag_test] Core resumed after %d JTAG polls\n", i + 1);
			break;
		}
	}
	CHECK("core resumes via JTAG", resumed);

	// ---- Phase 9: Run to completion ----
	fprintf(tb.logfile, "[jtag_test] Running CPU to completion...\n");
	bool cpu_exited = false;
	for (int64_t i = 0; i < 2000; i++) {
		sys_clk_cycles(tb, args, memio, 1);
		if (memio.exit_req) {
			cpu_exited = true;
			fprintf(tb.logfile, "[jtag_test] CPU exited with code %d after " I64_FMT " cycles\n",
				memio.exit_code, i + 1);
			break;
		}
	}
	CHECK("CPU exits after JTAG resume", cpu_exited);
	CHECK("CPU exit code is 0 (PASS)", cpu_exited && memio.exit_code == 0);

	// ---- Summary ----
	fprintf(tb.logfile, "\n========================================\n");
	fprintf(tb.logfile, " JTAG debug test: %d/%d tests passed\n", passed_tests, total_tests);
	fprintf(tb.logfile, "========================================\n");

	if (test_result == 0) {
		fprintf(tb.logfile, "CPU requested halt. Exit code 0\n");
	} else {
		fprintf(tb.logfile, "CPU requested halt. Exit code 1\n");
	}
	fprintf(tb.logfile, "Ran for " I64_FMT " cycles\n", tb.cycle);

	tb.finish(args);
	return test_result;
}
